### ISSUE TITLE
Using MultiWiiNode.hpp

### ISSUE THREAD

**Issue by darebear** [christianrauch/multiwii_ros2#1]
Hello Christian,

First, thank you for these repositories and nodes. I'm trying to include MultiWiiNode.hpp in an example ROS2 package but am not able to do so. When I try, I get the "MultiWiiNode.hpp" file not found build error. Can you provide some insight into how to include this header file or the library into another ROS2 package? 

Thank you.

**Comment by christianrauch** [comment]
The header `MultiWiiNode.hpp` is not installed, it's only used for the ROS2 node.

Why do you want to include the header directly?

**Comment by darebear** [comment]
Thank you for the quick reply. 

Maybe I've misunderstood the way the node works, but the reason I want to include the header directly is so that I could subscribe to the different topics. My understanding was that I would have to instantiate a MultiWiiNode class to then subscribe (MultiWiiNode::subscribe) to the desired topics, is this incorrect? 

Addition: one of the reasons I thought about the node in this form is that when I run the node, and try to "echo" from it, I cannot see the node publishing topics.

**Comment by christianrauch** [comment]
No. The `MultiWiiNode` is derived from a `rclcpp::Node`. You can use it in the same way that you can use other ROS2 composable nodes. You start the driver node, it will handle the communication with the flight controller (via MSP) and subscribe and publish via ROS topics.

The `MultiWiiNode` is instantiated in `multiwii_node.cpp`. You can use simply by running the executable `multiwii_node`.

**Comment by darebear** [comment]
Thanks, I'm a ROS/ROS2 newb, I will try this.

**Comment by christianrauch** [comment]
> Thanks, I'm a ROS/ROS2 newb, I will try this.

I suggest starting with https://docs.ros.org/en/foxy/Tutorials/Writing-A-Simple-Cpp-Publisher-And-Subscriber.html to get an overview on how to write and use a ROS2 node. The `MultiWiiNode` should work in the same way. Also have a look at https://answers.ros.org and https://robotics.stackexchange.com where people are answer questions about ROS.

I haven't used the node in a long time. There might be a lot of features missing that you require. When you are comfortable with ROS2, you can send a PR to implement functions that you need and I can have a look at this.

For now, I am going to close this issue since your question is quite ROS2 generic.
